---
ID: "15b25d98-5639-408e-821c-bcff58aa887e"
Parent: "3dc5b09d-5691-4728-bbc9-5b0c038766eb"
Template: "ec6d62a5-5d00-4329-8958-8ac1ad100ebb"
Path: /sitecore/content/Applications/Code Console/Code console/Ribbon/Settings
DB: core
SharedFields:
- ID: "12c1ceb4-f549-472a-97ed-99bff70eb84e"
  Hint: ID
  Value: ImageStrip
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180430T121538Z
    - ID: "5453dc07-6a17-48ba-8d05-17db90a2e795"
      Hint: Header
      Value: Settings
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
