---
ID: "a8346b3a-e840-4895-aa6f-596d1cfcc330"
Parent: "994986d5-9f9d-4bad-9915-a6e3f6e9468e"
Template: "8f3d8f9b-2d76-4ace-803f-35415d2b230a"
Path: /sitecore/content/Applications/Code Console/Code console/Ribbon/Home/Build
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180430T121601Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c95d21bd-66c3-444b-a37f-d346cbaf2b55"
      Hint: Header
      Value: Build
